### ISSUE TITLE
Delegated events don't work

### ISSUE THREAD

**Issue by ephickman** [mmikowski/jquery.event.ue#5]
The following works:
		jQueryMap.$contentPane.on ('click', '.spa-shell-menu-toggle', onTapToggle);
But the following doesn't:
		jQueryMap.$contentPane.on ('utap', '.spa-shell-menu-toggle', onTapToggle);
after removing the toggle from the contentPane, appending some new html to the content pane and prepending again the toggle.
Please, let me know how can I fix this directly in the source unless (you plan to fix this yourself, which would be great).

**Comment by artknight** [comment]
So, are you going to support this plugin further? Or is it dead?

**Comment by mmikowski** [comment]
I will continue to support this plugin, however, delegated events is not part of the feature set at this time.
